//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_Project_Reservations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public int roomId { get; set; }
        public System.DateTime dateFrom { get; set; }
        public System.DateTime dateTo { get; set; }
        public string description { get; set; }
        public int subjectId { get; set; }
        public int teacherId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
    }
}
